AWSTemplateFormatVersion: '2010-09-09'
Description: 'Phase 5: Closed-Loop Human Feedback Infrastructure for VLR Project'

Parameters:
  ProjectName:
    Type: String
    Default: 'VLR-Phase5'
    Description: 'Name of the project for resource tagging'
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'EC2 Key Pair for SSH access to instances'
  
  ModelBucket:
    Type: String
    Description: 'S3 bucket containing trained models'
  
  InstanceType:
    Type: String
    Default: 'g4dn.xlarge'
    AllowedValues: ['g4dn.xlarge', 'g4dn.2xlarge', 'p3.2xlarge', 'p3.8xlarge']
    Description: 'EC2 instance type for image generation'

Resources:
  # S3 Buckets
  GeneratedImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-generated-images-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: [GET, POST, PUT]
            AllowedHeaders: ['*']
            MaxAge: 3600
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ImageProcessingFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'generated_images/'
                  - Name: suffix
                    Value: '.png'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: 'Generated Images Storage'

  HumanFeedbackBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-human-feedback-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: 'Human Feedback Storage'

  # DynamoDB Tables
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-feedback-table'
      AttributeDefinitions:
        - AttributeName: feedback_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: triplet_id
          AttributeType: S
      KeySchema:
        - AttributeName: feedback_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TripletIndex
          KeySchema:
            - AttributeName: triplet_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: 'Feedback Data Storage'

  # SQS Queues
  ImageGenerationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-image-generation-queue'
      DelaySeconds: 0
      MaxReceiveCount: 3
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeoutSeconds: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImageGenerationDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  ImageGenerationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-image-generation-dlq'
      MessageRetentionPeriod: 1209600
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  FeedbackCollectionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-feedback-collection-queue'
      DelaySeconds: 0
      MessageRetentionPeriod: 1209600
      VisibilityTimeoutSeconds: 300
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # IAM Roles
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-EC2-Instance-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub '${GeneratedImagesBucket}/*'
                  - !Sub '${ModelBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !GetAtt GeneratedImagesBucket.Arn
                  - !Sub 'arn:aws:s3:::${ModelBucket}'
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt ImageGenerationQueue.Arn

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-EC2-Instance-Profile'
      Roles:
        - !Ref EC2InstanceRole

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-Lambda-Execution-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt FeedbackTable.Arn
                  - !Sub '${FeedbackTable.Arn}/index/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt GeneratedImagesBucket.Arn
                  - !Sub '${GeneratedImagesBucket}/*'
                  - !GetAtt HumanFeedbackBucket.Arn
                  - !Sub '${HumanFeedbackBucket}/*'

  # Lambda Functions
  FeedbackInterfaceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-feedback-interface'
      Runtime: python3.9
      Handler: index.serve_feedback_interface
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          # This will be replaced with actual code during deployment
          def serve_feedback_interface(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Function placeholder'
              }
      Environment:
        Variables:
          IMAGE_BUCKET: !Ref GeneratedImagesBucket
          FEEDBACK_TABLE: !Ref FeedbackTable
      Timeout: 30
      MemorySize: 512
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  GetTripletFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-get-triplet'
      Runtime: python3.9
      Handler: index.get_triplet
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def get_triplet(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Function placeholder'
              }
      Environment:
        Variables:
          IMAGE_BUCKET: !Ref GeneratedImagesBucket
          FEEDBACK_TABLE: !Ref FeedbackTable
      Timeout: 30
      MemorySize: 512
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  SubmitResponseFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-submit-response'
      Runtime: python3.9
      Handler: index.submit_response
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def submit_response(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Function placeholder'
              }
      Environment:
        Variables:
          FEEDBACK_TABLE: !Ref FeedbackTable
      Timeout: 30
      MemorySize: 512
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  SkipTripletFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-skip-triplet'
      Runtime: python3.9
      Handler: index.skip_triplet
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def skip_triplet(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Function placeholder'
              }
      Environment:
        Variables:
          FEEDBACK_TABLE: !Ref FeedbackTable
      Timeout: 30
      MemorySize: 512
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  ImageProcessingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-image-processing'
      Runtime: python3.9
      Handler: index.process_new_image
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def process_new_image(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Function placeholder'
              }
      Environment:
        Variables:
          IMAGE_BUCKET: !Ref GeneratedImagesBucket
          FEEDBACK_TABLE: !Ref FeedbackTable
      Timeout: 60
      MemorySize: 1024
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # API Gateway
  FeedbackAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-feedback-api'
      Description: 'API for human feedback collection'
      EndpointConfiguration:
        Types:
          - REGIONAL

  FeedbackAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - FeedbackInterfaceMethod
      - GetTripletMethod
      - SubmitResponseMethod
      - SkipTripletMethod
    Properties:
      RestApiId: !Ref FeedbackAPI
      StageName: 'prod'

  # API Gateway Resources
  FeedbackResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FeedbackAPI
      ParentId: !GetAtt FeedbackAPI.RootResourceId
      PathPart: 'feedback'

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FeedbackAPI
      ParentId: !GetAtt FeedbackAPI.RootResourceId
      PathPart: 'api'

  GetTripletResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FeedbackAPI
      ParentId: !Ref ApiResource
      PathPart: 'get-triplet'

  SubmitResponseResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FeedbackAPI
      ParentId: !Ref ApiResource
      PathPart: 'submit-response'

  SkipTripletResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FeedbackAPI
      ParentId: !Ref ApiResource
      PathPart: 'skip-triplet'

  # API Gateway Methods
  FeedbackInterfaceMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref FeedbackAPI
      ResourceId: !Ref FeedbackResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FeedbackInterfaceFunction.Arn}/invocations'

  GetTripletMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref FeedbackAPI
      ResourceId: !Ref GetTripletResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTripletFunction.Arn}/invocations'

  SubmitResponseMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref FeedbackAPI
      ResourceId: !Ref SubmitResponseResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SubmitResponseFunction.Arn}/invocations'

  SkipTripletMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref FeedbackAPI
      ResourceId: !Ref SkipTripletResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SkipTripletFunction.Arn}/invocations'

  # Lambda Permissions for API Gateway
  FeedbackInterfacePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FeedbackInterfaceFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FeedbackAPI}/*/*'

  GetTripletPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetTripletFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FeedbackAPI}/*/*'

  SubmitResponsePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SubmitResponseFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FeedbackAPI}/*/*'

  SkipTripletPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SkipTripletFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FeedbackAPI}/*/*'

  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ImageProcessingFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt GeneratedImagesBucket.Arn

  # Launch Template for EC2 Instances
  GenerationInstanceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${ProjectName}-generation-template'
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316  # Deep Learning AMI (will be updated)
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfile
        SecurityGroups:
          - default
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            
            # Install required packages
            pip install boto3 torch torchvision pillow numpy
            
            # Download worker script
            aws s3 cp s3://${ModelBucket}/scripts/step5_1_image_generation_worker.py /home/ec2-user/
            
            # Set environment variables
            echo "export GENERATION_QUEUE_URL=${ImageGenerationQueue}" >> /home/ec2-user/.bashrc
            echo "export IMAGE_BUCKET=${GeneratedImagesBucket}" >> /home/ec2-user/.bashrc
            echo "export MODEL_BUCKET=${ModelBucket}" >> /home/ec2-user/.bashrc
            echo "export MODEL_CHECKPOINT_KEY=models/stylegan2_hpe_final.pth" >> /home/ec2-user/.bashrc
            
            # Start worker service
            python3 /home/ec2-user/step5_1_image_generation_worker.py &
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Project
                Value: !Ref ProjectName
              - Key: Purpose
                Value: 'Image Generation Worker'

Outputs:
  GeneratedImagesBucket:
    Description: 'S3 bucket for generated images'
    Value: !Ref GeneratedImagesBucket
    Export:
      Name: !Sub '${AWS::StackName}-GeneratedImagesBucket'

  HumanFeedbackBucket:
    Description: 'S3 bucket for human feedback data'
    Value: !Ref HumanFeedbackBucket
    Export:
      Name: !Sub '${AWS::StackName}-HumanFeedbackBucket'

  FeedbackTable:
    Description: 'DynamoDB table for feedback storage'
    Value: !Ref FeedbackTable
    Export:
      Name: !Sub '${AWS::StackName}-FeedbackTable'

  ImageGenerationQueue:
    Description: 'SQS queue for image generation tasks'
    Value: !Ref ImageGenerationQueue
    Export:
      Name: !Sub '${AWS::StackName}-ImageGenerationQueue'

  FeedbackCollectionQueue:
    Description: 'SQS queue for feedback collection tasks'
    Value: !Ref FeedbackCollectionQueue
    Export:
      Name: !Sub '${AWS::StackName}-FeedbackCollectionQueue'

  FeedbackAPIEndpoint:
    Description: 'API Gateway endpoint for feedback collection'
    Value: !Sub 'https://${FeedbackAPI}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-FeedbackAPIEndpoint'

  FeedbackWebInterface:
    Description: 'Web interface URL for human feedback collection'
    Value: !Sub 'https://${FeedbackAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/feedback'
    Export:
      Name: !Sub '${AWS::StackName}-FeedbackWebInterface'

  LaunchTemplateId:
    Description: 'Launch template for generation instances'
    Value: !Ref GenerationInstanceLaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-LaunchTemplateId'
